spring:

  # Spring Config Properties
  config:
    import: optional:file:.env[.properties]

  # Spring Application Properties
  application:
    name: musicPub

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_POSTGRES_NAME}
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}

  # Force SQL Initialization
  sql:
    init:
      mode: always

  # JPA/HIBERNATE Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true